---
# tasks file for roles/postgressdb
#- name: install progress
#  command: "yum install -y postgresql-server"

- name: install postgres
  yum:
    name: postgresql-server
    state: latest
- name: enable apache at boot
  service:
    name: postgresql
    enabled: yes
- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: Check if PostgreSQL database is initialized. 
  stat: 
     path: "{{ postgresql_data_dir }}/PG_VERSION" 
  register: pgdata_dir_version 

# only run the next 2 tasks once!
- name: initilize postgres
  command: postgresql-setup initdb
  when: not pgdata_dir_version.stat.exists
- name: initilize postgres some more
  command: chkconfig postgresql on
- name: start postgres
  service:
    name: postgresql.service
    state: started
